# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWI4YzQ0NDZkMTE3NTcyYmMzODgyMDJhMThhYmJiNzIwN2NlMzVmZjliOGZkY2I1MDg0MzU0NTVmMWEwYjFlNTUwZGQ3NTMxNDQwYjc4YTJlY2NhMWYxZGQ1NmIzYzM2MDZkMDViMjE1NDllYjgzZDUyZTYxYWNiMmE0ZTcwM2E=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
